config_dir: /opt/rocm-7.0.3/libexec/rocprofiler-compute/rocprof_compute_soc/analysis_configs
device: -1
dispatch: null
filter_blocks: {}
format_rocprof_output: csv
hip_trace: false
join_type: grid
kernel: null
kernel_names: false
kokkos_trace: false
list_metrics: null
loglevel: 20
mem_level: ALL
mode: profile
name: fusion_matmulbias_32768x32768
no_roof: false
path: /workspace/user/workloads/fusion_matmulbias_32768x32768/MI300X_A1
pc_sampling_interval: 1048576
pc_sampling_method: stochastic
quiet: false
remaining:
- --
- python
- triton/matmulbias.py
- --M
- '32768'
- --N
- '32768'
- fusion
rocprofiler_sdk_library_path: /opt/rocm/lib/librocprofiler-sdk.so
roof_only: false
roofline_data_type:
- FP32
sort: kernels
spatial_multiplexing: null
specs: false
subpath: gpu
target: null
verbose: 0
