ARG EPEL_VERSION=10
FROM quay.io/centos/centos:${EPEL_VERSION}

ARG EPEL_VERSION
ARG ROCM_VERSION=7.0.3
ARG PYTHON_VERSION=3.12

# Install EPEL repo and software
ARG EPEL_REPO=https://dl.fedoraproject.org/pub/epel/epel-release-latest-${EPEL_VERSION}.noarch.rpm
RUN dnf -y install 'dnf-command(config-manager)' && \
	dnf -y config-manager --set-enabled crb && \
	dnf -y install ${EPEL_REPO} && \
    /usr/bin/crb enable && \
    dnf -y update && \
    dnf -y install gcc python${PYTHON_VERSION}-devel \
    python${PYTHON_VERSION}-pip \
    qt5-qtwayland xcb-util-cursor \
    vim && \
    dnf clean all && rm -rf /var/cache/dnf

# Install Jupyter Notebook dependencies
RUN dnf -y install pandoc texlive-adjustbox \
    texlive-collection-fontsrecommended texlive-eurosym texlive-fontspec \
    texlive-grffile texlive-jknapltx texlive-metafont texlive-parskip \
    texlive-soul texlive-tcolorbox texlive-titling texlive-upquote \
    texlive-ulem texlive-unicode-math texlive-xetex && \
    dnf clean all && rm -rf /var/cache/dnf

# Create the /workspace directory and set permissions
ARG WORKSPACE=/workspace
WORKDIR $WORKSPACE
RUN python${PYTHON_VERSION} -m pip install uv && \
    uv venv --python ${PYTHON_VERSION} --seed $WORKSPACE && \
    echo "unset BASH_ENV PROMPT_COMMAND ENV" >> ${WORKSPACE}/bin/activate

# Install python wheels
RUN uv pip install jupyter llnl-hatchet pandoc

# Install the AMD ROCm Repo and GPG key
ARG AMDGPU_INSTALL_URL=https://repo.radeon.com/amdgpu-install/${ROCM_VERSION}/rhel
RUN source /etc/os-release && \
    if [ "$VERSION_ID" = "10.0" ]; then RHEL_VERSION=${VERSION_ID%.*}; else RHEL_VERSION=${VERSION_ID}; fi; \
    AMDGPU_INSTALL_RPM=$(curl -s ${AMDGPU_INSTALL_URL}/${RHEL_VERSION}/ | grep href | sed -e 's/.*href="//' -e 's/".*//' |grep "amdgpu-install-${ROCM_VERSION%.*}.*${PLATFORM_ID#*:}.noarch.rpm") && \
    dnf -y install ${AMDGPU_INSTALL_URL}/${RHEL_VERSION}/${AMDGPU_INSTALL_RPM}

# Install the ROCm rpms
RUN dnf -y install --nodocs --setopt=install_weak_deps=False \
    amd-smi-lib rocminfo miopen-hip rocm-core rocm-hip-libraries rocm-developer-tools rocprofiler-compute && \
    dnf clean all && rm -rf /var/cache/yum

# Install the python dependencies for these tools
RUN if [ -f /opt/rocm-${ROCM_VERSION}/libexec/rocprofiler-compute/requirements.txt ]; then \
        uv pip install -r /opt/rocm-${ROCM_VERSION}/libexec/rocprofiler-compute/requirements.txt; \
    fi
RUN if [ -f /opt/rocm/share/amd_smi ]; then \
        uv pip install /opt/rocm/share/amd_smi; \
    fi

# Install torch (release or nightly if available)
ARG PIP_TORCH_INDEX_URL=https://download.pytorch.org/whl
RUN TORCH_ROCM_VERSION="$(echo "$ROCM_VERSION" | sed -e 's/\([0-9]\.[0-9]\).*/\1/')"; \
    if curl -o /dev/null -s -f -r 0-0 "${PIP_TORCH_INDEX_URL}/rocm${TORCH_ROCM_VERSION}"; then \
        echo "Installing torch rocm release"; \
        uv pip install --index-url="${PIP_TORCH_INDEX_URL}/rocm${TORCH_ROCM_VERSION}" torch; \
    elif curl -o /dev/null -s -f -r 0-0 "${PIP_TORCH_INDEX_URL}/nightly/rocm${TORCH_ROCM_VERSION}"; then \
        echo "Installing torch rocm nightly"; \
        uv pip install --index-url="${PIP_TORCH_INDEX_URL}/nightly/rocm${TORCH_ROCM_VERSION}" torch; \
    else \
        echo "ERROR: No torch backend available for ROCm ${TORCH_ROCM_VERSION}"; \
        exit 1; \
    fi

# Ensure any additional packages or specific package versions are installed
COPY containerfiles/rocm_requirements.txt /rocm_requirements.txt
RUN uv pip install -r /rocm_requirements.txt

ARG NOTEBOOK_PORT=8888
EXPOSE ${NOTEBOOK_PORT}

ENV BASH_ENV=${WORKSPACE}/bin/activate \
    ENV=${WORKSPACE}/bin/activate \
    LANG=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    ROCM_PATH=/opt/rocm \
    LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/opt/rocm/lib:/opt/rocm/llvm/lib \
    PATH=${WORKSPACE}/bin:/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH \
    PIP_PREFIX=$WORKSPACE \
    PROMPT_COMMAND=". ${WORKSPACE}/bin/activate" \
    PYTHON_VERSION=$PYTHON_VERSION \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=${WORKSPACE}/lib/python${PYTHON_VERSION}/site-packages \
    NOTEBOOK_PORT=${NOTEBOOK_PORT} \
    TRITON_HOME=$WORKSPACE \
    UV_HTTP_TIMEOUT=60 \
    WORKSPACE=$WORKSPACE \
    ROCM_VERSION=$ROCM_VERSION \
    XDG_CACHE_HOME=$WORKSPACE

WORKDIR ${WORKSPACE}/user

COPY --chmod=0755 containerfiles/start_jupyter.sh /usr/local/bin/start_jupyter
COPY --chmod=0755 containerfiles/entrypoint.sh.rocm /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
